### ISSUE TITLE
[Bug Report] Wayland mouse input problems

### ISSUE THREAD

**Issue by viridivn** [Amulet-Team/Amulet-Map-Editor#976]
### Current Behaviour:
When running under wayland, mouse input is very erratic and has an unusably high sensitivity. The further the mouse pointer is from the center of the screen, the worse the problem becomes. The video is even with sensitivity set to 1, the lowest option.

### Expected behavior:

The mouse input runs at a reasonable rate and is easy to use.

### Steps To Reproduce:

Launch program under wayland (I used Hyprland, on arch linux), make sure the program does not run under xwayland.
Load a world and try using the mouse to rotate the viewport (right click + drag)

### Environment:

- OS: Linux
- Minecraft Platform: Java 
- Minecraft Version: 1.20.1
- Amulet Version: 0.10.19

### Additional context
The problem does not occur under Xwayland, confirming it is something to do with wayland

gentlegiantJGC edit:
[Here is the code](https://github.com/Amulet-Team/Amulet-Map-Editor/blob/5ede8eda544df7ec1a4335376ec768bb255b7235/amulet_map_editor/programs/edit/api/behaviour/camera_behaviour.py#L107C0-L112C70) that manages mouse movement if anyone wants to try and solve this. I don't have access to wayland to debug this.

### Screenshots

https://github.com/Amulet-Team/Amulet-Map-Editor/assets/42524580/c3827f45-8995-45d7-b672-31e39ec44879

**Comment by gentlegiantJGC** [comment]
I am surprised no one has reported this sooner.
This is probably because wayland does not support teleporting the mouse.

**Comment by vaxerski** [comment]
If you are the focused surface, it definitely does. See https://wayland.app/protocols/pointer-constraints-unstable-v1

**Comment by brighamcampbell** [comment]
This bug is affecting my usage of amulet too. I'll try switching to switch while using amulet until a fix is available...

**Comment by LAHarbottle** [comment]
Still happening as of Amulet version 0.10.41 and Wayland version 1.23.1-1.1 (latest)

**Comment by gentlegiantJGC** [comment]
If you know how to solve it please submit a pull request.
I think this requires interacting directly with the wayland API that wxPython doesn't expose.

**Comment by ellisgl** [comment]
Maybe something in this thread? https://stackoverflow.com/questions/59688343/wxpython-on-wayland-is-unable-to-interact-with-screen-coordinates-move-a-window

**Comment by Fivebuss** [comment]
Still a problem on manjaro wayland, temporarily forcing xwayland as @ellisgl suggested fixes some but not all the problems
